/*
 * generated by Xtext
 */
package org.efaps.eql.ui.contentassist;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * See
 * https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-
 * assist on how to customize the content assistant.
 */
@Deprecated
public class EQLProposalProvider
{

    /** The log. */
    private static Logger LOG = LoggerFactory.getLogger(EQLProposalProvider.class);
}
