/*
 * Copyright © 2003 - 2024 The eFaps Team (-)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * generated by Xtext
 */
package org.efaps.eql.ui.contentassist;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * See
 * https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-
 * assist on how to customize the content assistant.
 */
@Deprecated
public class EQLProposalProvider
{

    /** The log. */
    private static Logger LOG = LoggerFactory.getLogger(EQLProposalProvider.class);
}
